### create data
POST http://localhost:8080/data
Content-Type: application/json

{
  "value": {{$randomInt}}
}

### list data
GET http://localhost:8080/data?limit=10&offset=0
Accept: application/json

### get data by id
GET http://localhost:8080/data/1
Accept: application/json

### update data by id
PUT http://localhost:8080/data/1
Content-Type: application/json

{
  "value": {{$randomInt}}
}

### delete data by id
DELETE http://localhost:8080/data/1
